### ISSUE TITLE
Methods need work

### ISSUE THREAD

**Issue by misterfifths** [learn-co-curriculum/objc-deli#11]
Hm... the methods in this one and what they do/return are ... weird.
A lot of them take mutable arrays, but are expected to return arrays... there is a 99% chance the student is going to modify the array argument, so why return it, too? If we don't want them to modify the argument, we shouldn't be passing a mutable array.... weird.
Also, I'd expect a method called `takeANumber...` to return a number. But... it returns an array... weird.

So some thoughts:

- How important is teaching return values at this point? If it's not, I think most of these methods make a ton more sense as void.
- `takeANumberWithDeliLine:name:` should maybe be `addCustomerNamed:toDeliLine:`, and return void?
- `nowServingWithDeliLine:` is a totally weird name. `serveNextCustomerInDeliLine:` makes much more sense to me. Same issue as the other methods with its return value.
- `deliLine:` is also a totally weird name for something that formats an array (not to mention that there's the definite potential that they'll have a property named `deliLine`, so having `deliLine` (the getter) and `deliLine:` (the method) would be super confusing). `stringWithDeliLine:` or `formatDeliLine:` would be much better. Also they don't use this method anywhere...

A thought:
Maybe this gets reorganized like this: the method `addCustomer...` could stay `takeANumber...` and actually *return* the position the new customer received in line. `serveNextCustomer...` could print out whose getting served, and then the remaining line, using their `stringWithDeliLine:` method. That feels much less contrived to me.

**Comment by markedwardmurray** [comment]
Methods renamed in rewrite.
