### ISSUE TITLE
needs prev short labs

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/objc-deli#14]
feel like I can't solve this on my own because I haven't practiced the building blocks enough. Would be good to have: 

* interpolated strings
* made mutable strings, converted them to NSString
* build for loops

@markedwardmurray

**Comment by AnnJohn** [comment]
Iceboxing for now @markedwardmurray close when you're done with the issue

**Comment by markedwardmurray** [comment]
@AnnJohn 

This has been addressed overall with the following new labs:

https://github.com/learn-co-curriculum/objc-interpolate
https://github.com/learn-co-curriculum/xcode-warnings-errors
https://github.com/learn-co-curriculum/objc-simple-math
https://github.com/learn-co-curriculum/objc-parrot
https://github.com/learn-co-curriculum/objc-speaking-grandma
https://github.com/learn-co-curriculum/objc-fizzbuzz
https://github.com/learn-co-curriculum/objc-palindrome-detector
https://github.com/learn-co-curriculum/objc-palindrome-inspector
