### ISSUE TITLE
needs more explicit instructions

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/objc-deli#15]
instructions great for in-person experience but we need to be more hand-holdy for prework/public track. 

@markedwardmurray

**Comment by AnnJohn** [comment]
Iceboxing now @markedwardmurray  close when you're done with the issue

**Comment by markedwardmurray** [comment]
@AnnJohn This lab is now being used as the qualifying assessment for the immersive and is intentionally a challenge. It serves as half-way capstone lab for the fundamentals unit that should be straightforward for students who have absorbed the material.
