### ISSUE TITLE
Links to Further Reading on Learn Public Track Point to flatiron-school-curriculum

### ISSUE THREAD

**Issue by JessRudder** [learn-co-curriculum/objc-deli#6]
The reading on Learn (not sure where it is in this repo as it's not part of this readme) tells learns to check out links on "Sorting Basics" (https://github.com/flatiron-school-curriculum/reading-ios-sorting-basic) and "Filtering Basics" (https://github.com/flatiron-school-curriculum/reading-ios-filtering-basic)

Both of those links are for the flatiron school curriculum repo which most students won't have access to.

Also, those readings reference using Cocoa, but, other than a brief mention during the setup process, the Learn curriculum hasn't gone into what that means.

**Comment by markedwardmurray** [comment]
The links to future readings have been removed in the rewrite. Thanks!
